### ISSUE TITLE
Remote server compilation error

### ISSUE THREAD

**Issue by eschlaf2** [magland/mountainlab#197]
Hello, I get the following errors when I run ./compile_components.sh on a remote server. I have nodejs and qt5 loaded as modules and fftw is installed locally. I don't have root access.

Any help you can give is greatly appreciated!!

************************************************************
Project MESSAGE: Enabling mdaconvert
Project MESSAGE: Enabling mda
Project MESSAGE: Enabling mountainprocess
Project MESSAGE: Enabling mountainsort
Project MESSAGE: Enabling prv
Project MESSAGE: Enabling mountainsort2
Project MESSAGE: Enabling mountainsort3
Project MESSAGE: Enabling mountainview
Project MESSAGE: Enabling mountaincompare
Project MESSAGE: Enabling spikeview1
Reading /project/ecog/emily/mountainlab/cpp/mlcommon/src/mlcommon.pro
Reading /project/ecog/emily/mountainlab/cpp/mlconfig/src/mlconfig.pro
Reading /project/ecog/emily/mountainlab/cpp/mdaconvert/src/mdaconvert.pro
Reading /project/ecog/emily/mountainlab/cpp/mda/src/mda.pro
Reading /project/ecog/emily/mountainlab/cpp/mountainprocess/src/mountainprocess.pro
Reading /project/ecog/emily/mountainlab/cpp/mountainsort/src/mountainsort.pro
Reading /project/ecog/emily/mountainlab/cpp/prv/src/prv.pro
Reading /project/ecog/emily/mountainlab/packages/mountainsort2/src/mountainsort2.pro
Reading /project/ecog/emily/mountainlab/packages/mountainsort3/src/mountainsort3.pro
Reading /project/ecog/emily/mountainlab/cpp/mvcommon/src/mvcommon.pro
Reading /project/ecog/emily/mountainlab/cpp/mountainview/src/mountainview.pro
Reading /project/ecog/emily/mountainlab/cpp/mountaincompare/src/mountaincompare.pro
Reading /project/ecog/emily/mountainlab/packages/spikeview1/src/spikeview1.pro
Project MESSAGE: Enabling mdaconvert
Project MESSAGE: Enabling mda
Project MESSAGE: Enabling mountainprocess
Project MESSAGE: Enabling mountainsort
Project MESSAGE: Enabling prv
Project MESSAGE: Enabling mountainsort2
Project MESSAGE: Enabling mountainsort3
Project MESSAGE: Enabling mountainview
Project MESSAGE: Enabling mountaincompare
Project MESSAGE: Enabling spikeview1
sha1sum: cpp/mountainprocess/bin/mountainprocess: No such file or directory
Building with 1 parallel jobs
cd cpp/mlcommon/src/ && ( test -e Makefile.mlcommon || /share/pkg/qt/5.4.2/install/bin/qmake /project/ecog/emily/mountainlab/cpp/mlcommon/src/mlcommon.pro -o Makefile.mlcommon ) && make -f Makefile.mlcommon 
make[1]: Entering directory `/project/ecog/emily/mountainlab/cpp/mlcommon/src'
g++ -c -pipe -O2 -fPIC -std=c++0x -Wall -W -D_REENTRANT -DUSE_REMOTE_READ_MDA -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../include -I../include/mda -I../include/cachemanager -I../include/taskprogress -I../include/mlnetwork -I../include/componentmanager -I/share/pkg/qt/5.4.2/install/include -I/share/pkg/qt/5.4.2/install/include/QtNetwork -I/share/pkg/qt/5.4.2/install/include/QtCore -I../build -I/share/pkg/qt/5.4.2/install/mkspecs/linux-g++ -o ../build/mlcommon.o mlcommon.cpp
In file included from mlcommon.cpp:9:0:
../include/taskprogress/taskprogress.h:178:19: error: ISO C++ forbids declaration of 'Q_ENUM' with no type [-fpermissive]
     Q_ENUM(LogType)
                   ^
../include/taskprogress/taskprogress.h:178:19: error: expected ';' at end of member declaration
mlcommon.cpp: In function 'double MLCompute::sum(const QVector<double>&)':
mlcommon.cpp:406:12: error: 'accumulate' is not a member of 'std'
     return std::accumulate(X.constBegin(), X.constEnd(), 0.0);
            ^~~
mlcommon.cpp: In function 'double MLCompute::stdev(const QVector<double>&)':
mlcommon.cpp:419:21: error: 'inner_product' is not a member of 'std'
     double sumsqr = std::inner_product(X.constBegin(), X.constEnd(), X.constBegin(), 0.0);
                     ^~~
mlcommon.cpp:420:18: error: 'accumulate' is not a member of 'std'
     double sum = std::accumulate(X.constBegin(), X.constEnd(), 0.0);
                  ^~~
mlcommon.cpp: In function 'double MLCompute::dotProduct(const QVector<double>&, const QVector<double>&)':
mlcommon.cpp:433:12: error: 'inner_product' is not a member of 'std'
     return std::inner_product(X1.constBegin(), X1.constEnd(), X2.constBegin(), 0.0);
            ^~~
mlcommon.cpp: In function 'double MLCompute::dotProduct(const QVector<float>&, const QVector<float>&)':
mlcommon.cpp:445:12: error: 'inner_product' is not a member of 'std'
     return std::inner_product(X1.constBegin(), X1.constEnd(), X2.constBegin(), 0.0);
            ^~~
mlcommon.cpp: In function 'double MLCompute::dotProduct(bigint, const double*, const double*)':
mlcommon.cpp:480:12: error: 'inner_product' is not a member of 'std'
     return std::inner_product(X1, X1 + N, X2, 0.0);
            ^~~
mlcommon.cpp: In function 'double MLCompute::dotProduct(bigint, const float*, const float*)':
mlcommon.cpp:486:12: error: 'inner_product' is not a member of 'std'
     return std::inner_product(X1, X1 + N, X2, 0.0);
            ^~~
mlcommon.cpp: In function 'double MLCompute::sum(bigint, const double*)':
mlcommon.cpp:498:12: error: 'accumulate' is not a member of 'std'
     return std::accumulate(X, X + N, 0.0);
            ^~~
mlcommon.cpp: In function 'double MLCompute::sum(bigint, const float*)':
mlcommon.cpp:679:12: error: 'accumulate' is not a member of 'std'
     return std::accumulate(X, X + N, 0.0);
            ^~~
make[1]: *** [../build/mlcommon.o] Error 1
make[1]: Leaving directory `/project/ecog/emily/mountainlab/cpp/mlcommon/src'
make: *** [sub-cpp-mlcommon-src-mlcommon-pro-make_first-ordered] Error 2
Problem in compilation.
************************************************************

**Comment by magland** [comment]
what branch are you on?

**Comment by eschlaf2** [comment]
ms3

**Comment by wysota** [comment]
Please run gcc --version (note the two dashes) and post the output.

**Comment by eschlaf2** [comment]
It's version 6.2.0. I did 'make clean' and then tried with 7.2 as well and got the following.
[compile_gcc7.txt](https://github.com/magland/mountainlab/files/1464120/compile_gcc7.txt)

**Comment by wysota** [comment]
Try newer (5.5+) Qt version if you can. If not or if it doesn't work, we'll try something different.

**Comment by eschlaf2** [comment]
We are still working on getting Qt 5.5+ on the cluster here (I am told that newer versions of Qt require CentOS 7 and we have CentOS 6). In the meantime, the program is running in a local virtual environment and it's working well so far. I'll update if we get it working on the cluster. Thanks for your help!!
